steps:
    # build the client container image
  - name: "gcr.io/cloud-builders/docker"
    dir: client
    args: ["build", "-t", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/client:$SHORT_SHA", "."]
    id: Build client
    # push client container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/client:$SHORT_SHA"]
    id: Push client
    # build the nginx container image
  - name: "gcr.io/cloud-builders/docker"
    dir: nginx
    args: ["build", "-t", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/nginx:$SHORT_SHA", "."]
    id: Build nginx
    # push nginx container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/nginx:$SHORT_SHA"]
    id: Push nginx
    # build the server container image
  - name: "gcr.io/cloud-builders/docker"
    dir: server
    args: ["build", "-t", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/server:$SHORT_SHA", "."]
    id: Build server
    # push server container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/server:$SHORT_SHA"]
    id: Push server
    # build the worker container image
  - name: "gcr.io/cloud-builders/docker"
    dir: worker
    args: ["build", "-t", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/worker:$SHORT_SHA", "."]
    id: Build worker
    # push worker container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/worker:$SHORT_SHA"]
    id: Push worker
    # deploy images to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: deploy client to GKE
    args:
    - run
    - --filename=kubernetes/client.yaml
    - --image=gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/client:$SHORT_SHA
    - --location=europe-west2
    - --cluster=cluster-1