apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-calc-apiserver-deployment
  namespace: fib-calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fib-calc
      fib-calc-component: api
  template:
    metadata:
      labels:
        app: fib-calc
        fib-calc-component: api
    spec:
      containers:
      - name: nginx
        image: gcr.io/sam-sandbox-243911/github.com/samweeks92/overly-complicated-fibonacci-calculator/apiserver:1.0
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: postgres
              key: db_host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: postgres
              key: port
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PORT
        ports:
        - name: container-port
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: fib-calc
spec:
  selector:
    app: fib-calc
    fib-calc-component: api
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000