apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: fib-calc-ingress
spec:
  domains:
    #edit this to be the name of the domain that you have registered the static IP against
    - fib-calc.samweeks.london
---    
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fib-calc-ingress
  namespace: fib-calc
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: "fib-ingress-ip"
    nginx.ingress.kubernetes.io/rewrite-target: /
    networking.gke.io/managed-certificates: fib-calc-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: client
          servicePort: 3000
      - path: /api/
        backend:
          serviceName: api
          servicePort: 5000

      